language: java

jdk:
 - oraclejdk8
 
sudo: required
addons:
 apt:
  packages:
   - oracle-java8-installer

# safe list: add here branches you want to verify the build & tests will pass
branches:
 only:
  - master


before_install:
# Create an environment variable for the correct distribution
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"

# Add the Cloud SDK distribution URI as a package source
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Import the Google Cloud Platform public key
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# Update the package list and install the Cloud SDK
- sudo apt-get update && sudo apt-get install google-cloud-sdk

- gcloud auth activate-service-account --key-file upandgo-f116a2b8afe5.json




# add this if you use maven for your project and want to verify mvn build is successful and all unit tests pass.
script:
 - gcloud auth application-default login
 - mvn test
 - mvn cobertura:cobertura


# running coverage tool
after_success:
  - bash <(curl -s https://codecov.io/bash)
