codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project: off
    patch: off
    changes: no
  

# Don't post a comment on pull requests.
comment: off

  

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
