coverage:
  paths:
	- src/main/java/model/**/*
	- "src/main/java/model/**/*"
	- src/main/java/model
  - !"src/main/java/model/"
   - !"src/main/java/model"
   - !"src/main/java/model/.*"
	- !"src/main/java/model/*"
	- !"main/java/model/*"
	- !"java/model/*"
	- !"model/*"
   - !src/main/java/model/.*
   - !src/main/java/model/.*
   - !view/.*
   - !"src/main/java/model/"
   - !"src/main/java/model"
   - !"src/main/java/model/.*"


codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project: off
    patch: off
    changes: no
  ignore: 
   - "src/main/java/model/"
   - "src/main/java/model"
   - "src/main/java/model/.*"
	- "src/main/java/model/*"
	- "main/java/model/*"
	- "java/model/*"
	- "model/*"
   - src/main/java/model/.*
   - src/main/java/model/.*
   - view/.*
   - "src/main/java/model/"
   - "src/main/java/model"
   - "src/main/java/model/.*"

# Don't post a comment on pull requests.
comment: off

  

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
